#ifndef SCIOSENSE_UFC23_MACROS_H_
#define SCIOSENSE_UFC23_MACROS_H_

//// Register UFC23_CR_FRU_IFH (0xA0)
#define UFC23_C_IRQ_EN_BL_DONE_SET(__Val__)             (((__Val__) <<  UFC23_C_IRQ_EN_BL_DONE_Pos)         &   UFC23_C_IRQ_EN_BL_DONE_Msk)
#define UFC23_C_IRQ_EN_BL_DONE_GET(__Val__)             (((__Val__) &   UFC23_C_IRQ_EN_BL_DONE_Msk)         >>  UFC23_C_IRQ_EN_BL_DONE_Pos)
#define UFC23_C_IRQ_EN_MIS_DONE_SET(__Val__)            (((__Val__) <<  UFC23_C_IRQ_EN_MIS_DONE_Pos)        &   UFC23_C_IRQ_EN_MIS_DONE_Msk)
#define UFC23_C_IRQ_EN_MIS_DONE_GET(__Val__)            (((__Val__) &   UFC23_C_IRQ_EN_MIS_DONE_Msk)        >>  UFC23_C_IRQ_EN_MIS_DONE_Pos)
#define UFC23_C_IRQ_EN_MCS_DONE_SET(__Val__)            (((__Val__) <<  UFC23_C_IRQ_EN_MCS_DONE_Pos)        &   UFC23_C_IRQ_EN_MCS_DONE_Msk)
#define UFC23_C_IRQ_EN_MCS_DONE_GET(__Val__)            (((__Val__) &   UFC23_C_IRQ_EN_MCS_DONE_Msk)        >>  UFC23_C_IRQ_EN_MCS_DONE_Pos)
#define UFC23_C_IRQ_EN_MC_BATCH_DONE_SET(__Val__)       (((__Val__) <<  UFC23_C_IRQ_EN_MC_BATCH_DONE_Pos)   &   UFC23_C_IRQ_EN_MC_BATCH_DONE_Msk)
#define UFC23_C_IRQ_EN_MC_BATCH_DONE_GET(__Val__)       (((__Val__) &   UFC23_C_IRQ_EN_MC_BATCH_DONE_Msk)   >>  UFC23_C_IRQ_EN_MC_BATCH_DONE_Pos)
#define UFC23_C_IRQ_EN_STASK_DONE_SET(__Val__)          (((__Val__) <<  UFC23_C_IRQ_EN_STASK_DONE_Pos)      &   UFC23_C_IRQ_EN_STASK_DONE_Msk)
#define UFC23_C_IRQ_EN_STASK_DONE_GET(__Val__)          (((__Val__) &   UFC23_C_IRQ_EN_STASK_DONE_Msk)      >>  UFC23_C_IRQ_EN_STASK_DONE_Pos)
#define UFC23_C_IRQ_EN_USM_PAUSE_ERR_SET(__Val__)       (((__Val__) <<  UFC23_C_IRQ_EN_USM_PAUSE_ERR_Pos)   &   UFC23_C_IRQ_EN_USM_PAUSE_ERR_Msk)
#define UFC23_C_IRQ_EN_USM_PAUSE_ERR_GET(__Val__)       (((__Val__) &   UFC23_C_IRQ_EN_USM_PAUSE_ERR_Msk)   >>  UFC23_C_IRQ_EN_USM_PAUSE_ERR_Pos)
#define UFC23_C_IRQ_EN_TSC_TMO_SET(__Val__)             (((__Val__) <<  UFC23_C_IRQ_EN_TSC_TMO_Pos)         &   UFC23_C_IRQ_EN_TSC_TMO_Msk)
#define UFC23_C_IRQ_EN_TSC_TMO_GET(__Val__)             (((__Val__) &   UFC23_C_IRQ_EN_TSC_TMO_Msk)         >>  UFC23_C_IRQ_EN_TSC_TMO_Pos)

//// Register UFC23_CR_FRU_EFH (0xA1)
#define UFC23_C_EF_EN_HCC_TDC_TMO_SET(__Val__)          (((__Val__) <<  UFC23_C_EF_EN_HCC_TDC_TMO_Pos)      &   UFC23_C_EF_EN_HCC_TDC_TMO_Msk)
#define UFC23_C_EF_EN_HCC_TDC_TMO_GET(__Val__)          (((__Val__) &   UFC23_C_EF_EN_HCC_TDC_TMO_Msk)      >>  UFC23_C_EF_EN_HCC_TDC_TMO_Pos)
#define UFC23_C_EF_EN_TM_TDC_TMO_SET(__Val__)           (((__Val__) <<  UFC23_C_EF_EN_TM_TDC_TMO_Pos)       &   UFC23_C_EF_EN_TM_TDC_TMO_Msk)
#define UFC23_C_EF_EN_TM_TDC_TMO_GET(__Val__)           (((__Val__) &   UFC23_C_EF_EN_TM_TDC_TMO_Msk)       >>  UFC23_C_EF_EN_TM_TDC_TMO_Pos)
#define UFC23_C_EF_EN_TM_OC_ERR_SET(__Val__)            (((__Val__) <<  UFC23_C_EF_EN_TM_OC_ERR_Pos)        &   UFC23_C_EF_EN_TM_OC_ERR_Msk)
#define UFC23_C_EF_EN_TM_OC_ERR_GET(__Val__)            (((__Val__) &   UFC23_C_EF_EN_TM_OC_ERR_Msk)        >>  UFC23_C_EF_EN_TM_OC_ERR_Pos)
#define UFC23_C_EF_EN_TM_SC_ERR_SET(__Val__)            (((__Val__) <<  UFC23_C_EF_EN_TM_SC_ERR_Pos)        &   UFC23_C_EF_EN_TM_SC_ERR_Msk)
#define UFC23_C_EF_EN_TM_SC_ERR_GET(__Val__)            (((__Val__) &   UFC23_C_EF_EN_TM_SC_ERR_Msk)        >>  UFC23_C_EF_EN_TM_SC_ERR_Pos)
#define UFC23_C_EF_EN_USM_HW_UP_ERR_SET(__Val__)        (((__Val__) <<  UFC23_C_EF_EN_USM_HW_UP_ERR_Pos)    &   UFC23_C_EF_EN_USM_HW_UP_ERR_Msk)
#define UFC23_C_EF_EN_USM_HW_UP_ERR_GET(__Val__)        (((__Val__) &   UFC23_C_EF_EN_USM_HW_UP_ERR_Msk)    >>  UFC23_C_EF_EN_USM_HW_UP_ERR_Pos)
#define UFC23_C_EF_EN_USM_HW_DN_ERR_SET(__Val__)        (((__Val__) <<  UFC23_C_EF_EN_USM_HW_DN_ERR_Pos)    &   UFC23_C_EF_EN_USM_HW_DN_ERR_Msk)
#define UFC23_C_EF_EN_USM_HW_DN_ERR_GET(__Val__)        (((__Val__) &   UFC23_C_EF_EN_USM_HW_DN_ERR_Msk)    >>  UFC23_C_EF_EN_USM_HW_DN_ERR_Pos)
#define UFC23_C_EF_EN_PW_UP_TDC_TMO_SET(__Val__)        (((__Val__) <<  UFC23_C_EF_EN_PW_UP_TDC_TMO_Pos)    &   UFC23_C_EF_EN_PW_UP_TDC_TMO_Msk)
#define UFC23_C_EF_EN_PW_UP_TDC_TMO_GET(__Val__)        (((__Val__) &   UFC23_C_EF_EN_PW_UP_TDC_TMO_Msk)    >>  UFC23_C_EF_EN_PW_UP_TDC_TMO_Pos)
#define UFC23_C_EF_EN_PW_DN_TDC_TMO_SET(__Val__)        (((__Val__) <<  UFC23_C_EF_EN_PW_DN_TDC_TMO_Pos)    &   UFC23_C_EF_EN_PW_DN_TDC_TMO_Msk)
#define UFC23_C_EF_EN_PW_DN_TDC_TMO_GET(__Val__)        (((__Val__) &   UFC23_C_EF_EN_PW_DN_TDC_TMO_Msk)    >>  UFC23_C_EF_EN_PW_DN_TDC_TMO_Pos)
#define UFC23_C_EF_EN_TOF_UP_TDC_TMO_SET(__Val__)       (((__Val__) <<  UFC23_C_EF_EN_TOF_UP_TDC_TMO_Pos)   &   UFC23_C_EF_EN_TOF_UP_TDC_TMO_Msk)
#define UFC23_C_EF_EN_TOF_UP_TDC_TMO_GET(__Val__)       (((__Val__) &   UFC23_C_EF_EN_TOF_UP_TDC_TMO_Msk)   >>  UFC23_C_EF_EN_TOF_UP_TDC_TMO_Pos)
#define UFC23_C_EF_EN_TOF_DN_TDC_TMO_SET(__Val__)       (((__Val__) <<  UFC23_C_EF_EN_TOF_DN_TDC_TMO_Pos)   &   UFC23_C_EF_EN_TOF_DN_TDC_TMO_Msk)
#define UFC23_C_EF_EN_TOF_DN_TDC_TMO_GET(__Val__)       (((__Val__) &   UFC23_C_EF_EN_TOF_DN_TDC_TMO_Msk)   >>  UFC23_C_EF_EN_TOF_DN_TDC_TMO_Pos)
#define UFC23_C_EF_EN_USM_UP_TMO_SET(__Val__)           (((__Val__) <<  UFC23_C_EF_EN_USM_UP_TMO_Pos)       &   UFC23_C_EF_EN_USM_UP_TMO_Msk)
#define UFC23_C_EF_EN_USM_UP_TMO_GET(__Val__)           (((__Val__) &   UFC23_C_EF_EN_USM_UP_TMO_Msk)       >>  UFC23_C_EF_EN_USM_UP_TMO_Pos)
#define UFC23_C_EF_EN_USM_DN_TMO_SET(__Val__)           (((__Val__) <<  UFC23_C_EF_EN_USM_DN_TMO_Pos)       &   UFC23_C_EF_EN_USM_DN_TMO_Msk)
#define UFC23_C_EF_EN_USM_DN_TMO_GET(__Val__)           (((__Val__) &   UFC23_C_EF_EN_USM_DN_TMO_Msk)       >>  UFC23_C_EF_EN_USM_DN_TMO_Pos)

//// Register UFC23_CR_GP_CTRL (0xA2)
#define UFC23_C_GPIO0_MODE_SET(__Val__)                 (((__Val__) <<  UFC23_C_GPIO0_MODE_Pos)             &   UFC23_C_GPIO0_MODE_Msk)
#define UFC23_C_GPIO0_MODE_GET(__Val__)                 (((__Val__) &   UFC23_C_GPIO0_MODE_Msk)             >>  UFC23_C_GPIO0_MODE_Pos)
#define UFC23_C_GPIO1_MODE_SET(__Val__)                 (((__Val__) <<  UFC23_C_GPIO1_MODE_Pos)             &   UFC23_C_GPIO1_MODE_Msk)
#define UFC23_C_GPIO1_MODE_GET(__Val__)                 (((__Val__) &   UFC23_C_GPIO1_MODE_Msk)             >>  UFC23_C_GPIO1_MODE_Pos)
#define UFC23_C_GPIO2_MODE_SET(__Val__)                 (((__Val__) <<  UFC23_C_GPIO2_MODE_Pos)             &   UFC23_C_GPIO2_MODE_Msk)
#define UFC23_C_GPIO2_MODE_GET(__Val__)                 (((__Val__) &   UFC23_C_GPIO2_MODE_Msk)             >>  UFC23_C_GPIO2_MODE_Pos)
#define UFC23_C_GPIO3_MODE_SET(__Val__)                 (((__Val__) <<  UFC23_C_GPIO3_MODE_Pos)             &   UFC23_C_GPIO3_MODE_Msk)
#define UFC23_C_GPIO3_MODE_GET(__Val__)                 (((__Val__) &   UFC23_C_GPIO3_MODE_Msk)             >>  UFC23_C_GPIO3_MODE_Pos)
#define UFC23_C_PRB_SEL_SET(__Val__)                    (((__Val__) <<  UFC23_C_PRB_SEL_Pos)                &   UFC23_C_PRB_SEL_Msk)
#define UFC23_C_PRB_SEL_GET(__Val__)                    (((__Val__) &   UFC23_C_PRB_SEL_Msk)                >>  UFC23_C_PRB_SEL_Pos)
#define UFC23_C_TST_STM_SET(__Val__)                    (((__Val__) <<  UFC23_C_TST_STM_Pos)                &   UFC23_C_TST_STM_Msk)
#define UFC23_C_TST_STM_GET(__Val__)                    (((__Val__) &   UFC23_C_TST_STM_Msk)                >>  UFC23_C_TST_STM_Pos)
#define UFC23_C_MISO_HZ_DIS_SET(__Val__)                (((__Val__) <<  UFC23_C_MISO_HZ_DIS_Pos)            &   UFC23_C_MISO_HZ_DIS_Msk)
#define UFC23_C_MISO_HZ_DIS_GET(__Val__)                (((__Val__) &   UFC23_C_MISO_HZ_DIS_Msk)            >>  UFC23_C_MISO_HZ_DIS_Pos)

//// Register UFC23_CR_PM (0xA3)
#define UFC23_C_LDO_RF_RATE_SET(__Val__)                (((__Val__) <<  UFC23_C_LDO_RF_RATE_Pos)            &   UFC23_C_LDO_RF_RATE_Msk)
#define UFC23_C_LDO_RF_RATE_GET(__Val__)                (((__Val__) &   UFC23_C_LDO_RF_RATE_Msk)            >>  UFC23_C_LDO_RF_RATE_Pos)
#define UFC23_C_VDD18_SW_MODE_SET(__Val__)              (((__Val__) <<  UFC23_C_VDD18_SW_MODE_Pos)          &   UFC23_C_VDD18_SW_MODE_Msk)
#define UFC23_C_VDD18_SW_MODE_GET(__Val__)              (((__Val__) &   UFC23_C_VDD18_SW_MODE_Msk)          >>  UFC23_C_VDD18_SW_MODE_Pos)

//// Register UFC23_CR_TSC (0xA4)
#define UFC23_C_USM_PAUSE_TSEL_SET(__Val__)             (((__Val__) <<  UFC23_C_USM_PAUSE_TSEL_Pos)         &   UFC23_C_USM_PAUSE_TSEL_Msk)
#define UFC23_C_USM_PAUSE_TSEL_GET(__Val__)             (((__Val__) &   UFC23_C_USM_PAUSE_TSEL_Msk)         >>  UFC23_C_USM_PAUSE_TSEL_Pos)
#define UFC23_C_USM_REPEAT_SET(__Val__)                 (((__Val__) <<  UFC23_C_USM_REPEAT_Pos)             &   UFC23_C_USM_REPEAT_Msk)
#define UFC23_C_USM_REPEAT_GET(__Val__)                 (((__Val__) &   UFC23_C_USM_REPEAT_Msk)             >>  UFC23_C_USM_REPEAT_Pos)
#define UFC23_C_USM_DIR_MODE_SET(__Val__)               (((__Val__) <<  UFC23_C_USM_DIR_MODE_Pos)           &   UFC23_C_USM_DIR_MODE_Msk)
#define UFC23_C_USM_DIR_MODE_GET(__Val__)               (((__Val__) &   UFC23_C_USM_DIR_MODE_Msk)           >>  UFC23_C_USM_DIR_MODE_Pos)
#define UFC23_C_USM_EDGE_MODE_SET(__Val__)              (((__Val__) <<  UFC23_C_USM_EDGE_MODE_Pos)          &   UFC23_C_USM_EDGE_MODE_Msk)
#define UFC23_C_USM_EDGE_MODE_GET(__Val__)              (((__Val__) &   UFC23_C_USM_EDGE_MODE_Msk)          >>  UFC23_C_USM_EDGE_MODE_Pos)
#define UFC23_C_LDO_STUP_TSEL_SET(__Val__)              (((__Val__) <<  UFC23_C_LDO_STUP_TSEL_Pos)          &   UFC23_C_LDO_STUP_TSEL_Msk)
#define UFC23_C_LDO_STUP_TSEL_GET(__Val__)              (((__Val__) &   UFC23_C_LDO_STUP_TSEL_Msk)          >>  UFC23_C_LDO_STUP_TSEL_Pos)
#define UFC23_C_LDO_FEP_MODE_SET(__Val__)               (((__Val__) <<  UFC23_C_LDO_FEP_MODE_Pos)           &   UFC23_C_LDO_FEP_MODE_Msk)
#define UFC23_C_LDO_FEP_MODE_GET(__Val__)               (((__Val__) &   UFC23_C_LDO_FEP_MODE_Msk)           >>  UFC23_C_LDO_FEP_MODE_Pos)
#define UFC23_C_TM_SQC_MODE_SET(__Val__)                (((__Val__) <<  UFC23_C_TM_SQC_MODE_Pos)            &   UFC23_C_TM_SQC_MODE_Msk)
#define UFC23_C_TM_SQC_MODE_GET(__Val__)                (((__Val__) &   UFC23_C_TM_SQC_MODE_Msk)            >>  UFC23_C_TM_SQC_MODE_Pos)

//// Register UFC23_CR_MCT (0xA5)
#define UFC23_C_MCYCLE_TIME_SET(__Val__)                (((__Val__) <<  UFC23_C_MCYCLE_TIME_Pos)            &   UFC23_C_MCYCLE_TIME_Msk)
#define UFC23_C_MCYCLE_TIME_GET(__Val__)                (((__Val__) &   UFC23_C_MCYCLE_TIME_Msk)            >>  UFC23_C_MCYCLE_TIME_Pos)
#define UFC23_C_MCYCLE_TAIL_SEL_SET(__Val__)            (((__Val__) <<  UFC23_C_MCYCLE_TAIL_SEL_Pos)        &   UFC23_C_MCYCLE_TAIL_SEL_Msk)
#define UFC23_C_MCYCLE_TAIL_SEL_GET(__Val__)            (((__Val__) &   UFC23_C_MCYCLE_TAIL_SEL_Msk)        >>  UFC23_C_MCYCLE_TAIL_SEL_Pos)
#define UFC23_C_MCT_EN_SET(__Val__)                     (((__Val__) <<  UFC23_C_MCT_EN_Pos)                 &   UFC23_C_MCT_EN_Msk)
#define UFC23_C_MCT_EN_GET(__Val__)                     (((__Val__) &   UFC23_C_MCT_EN_Msk)                 >>  UFC23_C_MCT_EN_Pos)

//// Register UFC23_CR_MRG (0xA6)
#define UFC23_C_USM_RATE_SET(__Val__)                   (((__Val__) <<  UFC23_C_USM_RATE_Pos)               &   UFC23_C_USM_RATE_Msk)
#define UFC23_C_USM_RATE_GET(__Val__)                   (((__Val__) &   UFC23_C_USM_RATE_Msk)               >>  UFC23_C_USM_RATE_Pos)
#define UFC23_C_ZCC_RATE_SET(__Val__)                   (((__Val__) <<  UFC23_C_ZCC_RATE_Pos)               &   UFC23_C_ZCC_RATE_Msk)
#define UFC23_C_ZCC_RATE_GET(__Val__)                   (((__Val__) &   UFC23_C_ZCC_RATE_Msk)               >>  UFC23_C_ZCC_RATE_Pos)
#define UFC23_C_VCCM_RATE_SET(__Val__)                  (((__Val__) <<  UFC23_C_VCCM_RATE_Pos)              &   UFC23_C_VCCM_RATE_Msk)
#define UFC23_C_VCCM_RATE_GET(__Val__)                  (((__Val__) &   UFC23_C_VCCM_RATE_Msk)              >>  UFC23_C_VCCM_RATE_Pos)
#define UFC23_C_HCC_RATE_SET(__Val__)                   (((__Val__) <<  UFC23_C_HCC_RATE_Pos)               &   UFC23_C_HCC_RATE_Msk)
#define UFC23_C_HCC_RATE_GET(__Val__)                   (((__Val__) &   UFC23_C_HCC_RATE_Msk)               >>  UFC23_C_HCC_RATE_Pos)
#define UFC23_C_FBC_RATE_SET(__Val__)                   (((__Val__) <<  UFC23_C_FBC_RATE_Pos)               &   UFC23_C_FBC_RATE_Msk)
#define UFC23_C_FBC_RATE_GET(__Val__)                   (((__Val__) &   UFC23_C_FBC_RATE_Msk)               >>  UFC23_C_FBC_RATE_Pos)
#define UFC23_C_TM_RATE_SET(__Val__)                    (((__Val__) <<  UFC23_C_TM_RATE_Pos)                &   UFC23_C_TM_RATE_Msk)
#define UFC23_C_TM_RATE_GET(__Val__)                    (((__Val__) &   UFC23_C_TM_RATE_Msk)                >>  UFC23_C_TM_RATE_Pos)

//// Register UFC23_CR_FEP_MCTRL (0xA7)
#define UFC23_C_FEP_4M_CLK_DIV_SET(__Val__)             (((__Val__) <<  UFC23_C_FEP_4M_CLK_DIV_Pos)         &   UFC23_C_FEP_4M_CLK_DIV_Msk)
#define UFC23_C_FEP_4M_CLK_DIV_GET(__Val__)             (((__Val__) &   UFC23_C_FEP_4M_CLK_DIV_Msk)         >>  UFC23_C_FEP_4M_CLK_DIV_Pos)
#define UFC23_C_ADC_ST_SET(__Val__)                     (((__Val__) <<  UFC23_C_ADC_ST_Pos)                 &   UFC23_C_ADC_ST_Msk)
#define UFC23_C_ADC_ST_GET(__Val__)                     (((__Val__) &   UFC23_C_ADC_ST_Msk)                 >>  UFC23_C_ADC_ST_Pos)
#define UFC23_C_FEP_STUP_TSEL_SET(__Val__)              (((__Val__) <<  UFC23_C_FEP_STUP_TSEL_Pos)          &   UFC23_C_FEP_STUP_TSEL_Msk)
#define UFC23_C_FEP_STUP_TSEL_GET(__Val__)              (((__Val__) &   UFC23_C_FEP_STUP_TSEL_Msk)          >>  UFC23_C_FEP_STUP_TSEL_Pos)
#define UFC23_C_USM_TMO_SEL_SET(__Val__)                (((__Val__) <<  UFC23_C_USM_TMO_SEL_Pos)            &   UFC23_C_USM_TMO_SEL_Msk)
#define UFC23_C_USM_TMO_SEL_GET(__Val__)                (((__Val__) &   UFC23_C_USM_TMO_SEL_Msk)            >>  UFC23_C_USM_TMO_SEL_Pos)
#define UFC23_C_TM_PORT_NO_SET(__Val__)                 (((__Val__) <<  UFC23_C_TM_PORT_NO_Pos)             &   UFC23_C_TM_PORT_NO_Msk)
#define UFC23_C_TM_PORT_NO_GET(__Val__)                 (((__Val__) &   UFC23_C_TM_PORT_NO_Msk)             >>  UFC23_C_TM_PORT_NO_Pos)
#define UFC23_C_TM_PORT_MODE_SET(__Val__)               (((__Val__) <<  UFC23_C_TM_PORT_MODE_Pos)           &   UFC23_C_TM_PORT_MODE_Msk)
#define UFC23_C_TM_PORT_MODE_GET(__Val__)               (((__Val__) &   UFC23_C_TM_PORT_MODE_Msk)           >>  UFC23_C_TM_PORT_MODE_Pos)
#define UFC23_C_TM_CYCLE_SEL_SET(__Val__)               (((__Val__) <<  UFC23_C_TM_CYCLE_SEL_Pos)           &   UFC23_C_TM_CYCLE_SEL_Msk)
#define UFC23_C_TM_CYCLE_SEL_GET(__Val__)               (((__Val__) &   UFC23_C_TM_CYCLE_SEL_Msk)           >>  UFC23_C_TM_CYCLE_SEL_Pos)
#define UFC23_C_TM_SQC_NO_SET(__Val__)                  (((__Val__) <<  UFC23_C_TM_SQC_NO_Pos)              &   UFC23_C_TM_SQC_NO_Msk)
#define UFC23_C_TM_SQC_NO_GET(__Val__)                  (((__Val__) &   UFC23_C_TM_SQC_NO_Msk)              >>  UFC23_C_TM_SQC_NO_Pos)
#define UFC23_C_HF_CLB_SEL_SET(__Val__)                 (((__Val__) <<  UFC23_C_HF_CLB_SEL_Pos)             &   UFC23_C_HF_CLB_SEL_Msk)
#define UFC23_C_HF_CLB_SEL_GET(__Val__)                 (((__Val__) &   UFC23_C_HF_CLB_SEL_Msk)             >>  UFC23_C_HF_CLB_SEL_Pos)
#define UFC23_C_HF_SERIAL_SET(__Val__)                  (((__Val__) <<  UFC23_C_HF_SERIAL_Pos)              &   UFC23_C_HF_SERIAL_Msk)
#define UFC23_C_HF_SERIAL_GET(__Val__)                  (((__Val__) &   UFC23_C_HF_SERIAL_Msk)              >>  UFC23_C_HF_SERIAL_Pos)
#define UFC23_C_HF_TRIM_SET(__Val__)                    (((__Val__) <<  UFC23_C_HF_TRIM_Pos)                &   UFC23_C_HF_TRIM_Msk)
#define UFC23_C_HF_TRIM_GET(__Val__)                    (((__Val__) &   UFC23_C_HF_TRIM_Msk)                >>  UFC23_C_HF_TRIM_Pos)
#define UFC23_C_HF_CALIB_MODE_SET(__Val__)              (((__Val__) <<  UFC23_C_HF_CALIB_MODE_Pos)          &   UFC23_C_HF_CALIB_MODE_Msk)
#define UFC23_C_HF_CALIB_MODE_GET(__Val__)              (((__Val__) &   UFC23_C_HF_CALIB_MODE_Msk)          >>  UFC23_C_HF_CALIB_MODE_Pos)
#define UFC23_C_HF_DCO_ENA_SET(__Val__)                 (((__Val__) <<  UFC23_C_HF_DCO_ENA_Pos)             &   UFC23_C_HF_DCO_ENA_Msk)
#define UFC23_C_HF_DCO_ENA_GET(__Val__)                 (((__Val__) &   UFC23_C_HF_DCO_ENA_Msk)             >>  UFC23_C_HF_DCO_ENA_Pos)

//// Register UFC23_CR_FEP_TDC_TRIM (0xA9)
#define UFC23_C_TDC_SEL_QHA1_SET(__Val__)               (((__Val__) <<  UFC23_C_TDC_SEL_QHA1_Pos)           &   UFC23_C_TDC_SEL_QHA1_Msk)
#define UFC23_C_TDC_SEL_QHA1_GET(__Val__)               (((__Val__) &   UFC23_C_TDC_SEL_QHA1_Msk)           >>  UFC23_C_TDC_SEL_QHA1_Pos)
#define UFC23_C_TDC_SEL_QHA2_SET(__Val__)               (((__Val__) <<  UFC23_C_TDC_SEL_QHA2_Pos)           &   UFC23_C_TDC_SEL_QHA2_Msk)
#define UFC23_C_TDC_SEL_QHA2_GET(__Val__)               (((__Val__) &   UFC23_C_TDC_SEL_QHA2_Msk)           >>  UFC23_C_TDC_SEL_QHA2_Pos)
#define UFC23_C_TDC_PHS_MODE_SET(__Val__)               (((__Val__) <<  UFC23_C_TDC_PHS_MODE_Pos)           &   UFC23_C_TDC_PHS_MODE_Msk)
#define UFC23_C_TDC_PHS_MODE_GET(__Val__)               (((__Val__) &   UFC23_C_TDC_PHS_MODE_Msk)           >>  UFC23_C_TDC_PHS_MODE_Pos)
#define UFC23_C_PHS_CELLS_SET(__Val__)                  (((__Val__) <<  UFC23_C_PHS_CELLS_Pos)              &   UFC23_C_PHS_CELLS_Msk)
#define UFC23_C_PHS_CELLS_GET(__Val__)                  (((__Val__) &   UFC23_C_PHS_CELLS_Msk)              >>  UFC23_C_PHS_CELLS_Pos)
#define UFC23_C_PHS_INCR_SET(__Val__)                   (((__Val__) <<  UFC23_C_PHS_INCR_Pos)               &   UFC23_C_PHS_INCR_Msk)
#define UFC23_C_PHS_INCR_GET(__Val__)                   (((__Val__) &   UFC23_C_PHS_INCR_Msk)               >>  UFC23_C_PHS_INCR_Pos)
#define UFC23_C_TDC_HR_ADJUST_SET(__Val__)              (((__Val__) <<  UFC23_C_TDC_HR_ADJUST_Pos)          &   UFC23_C_TDC_HR_ADJUST_Msk)
#define UFC23_C_TDC_HR_ADJUST_GET(__Val__)              (((__Val__) &   UFC23_C_TDC_HR_ADJUST_Msk)          >>  UFC23_C_TDC_HR_ADJUST_Pos)

//// Register UFC23_CR_USM_PROC (0xAA)
#define UFC23_C_USM_MASK_WIN_SET(__Val__)               (((__Val__) <<  UFC23_C_USM_MASK_WIN_Pos)           &   UFC23_C_USM_MASK_WIN_Msk)
#define UFC23_C_USM_MASK_WIN_GET(__Val__)               (((__Val__) &   UFC23_C_USM_MASK_WIN_Msk)           >>  UFC23_C_USM_MASK_WIN_Pos)
#define UFC23_C_USM_MHIT_BATCH_SET(__Val__)             (((__Val__) <<  UFC23_C_USM_MHIT_BATCH_Pos)         &   UFC23_C_USM_MHIT_BATCH_Msk)
#define UFC23_C_USM_MHIT_BATCH_GET(__Val__)             (((__Val__) &   UFC23_C_USM_MHIT_BATCH_Msk)         >>  UFC23_C_USM_MHIT_BATCH_Pos)
#define UFC23_C_USM_SENSOR_MODE_SET(__Val__)            (((__Val__) <<  UFC23_C_USM_SENSOR_MODE_Pos)        &   UFC23_C_USM_SENSOR_MODE_Msk)
#define UFC23_C_USM_SENSOR_MODE_GET(__Val__)            (((__Val__) &   UFC23_C_USM_SENSOR_MODE_Msk)        >>  UFC23_C_USM_SENSOR_MODE_Pos)
#define UFC23_C_USM_AM_MODE_SET(__Val__)                (((__Val__) <<  UFC23_C_USM_AM_MODE_Pos)            &   UFC23_C_USM_AM_MODE_Msk)
#define UFC23_C_USM_AM_MODE_GET(__Val__)                (((__Val__) &   UFC23_C_USM_AM_MODE_Msk)            >>  UFC23_C_USM_AM_MODE_Pos)
#define UFC23_C_USM_PWD_MODE_SET(__Val__)               (((__Val__) <<  UFC23_C_USM_PWD_MODE_Pos)           &   UFC23_C_USM_PWD_MODE_Msk)
#define UFC23_C_USM_PWD_MODE_GET(__Val__)               (((__Val__) &   UFC23_C_USM_PWD_MODE_Msk)           >>  UFC23_C_USM_PWD_MODE_Pos)
#define UFC23_C_ZCD_LVL_SET(__Val__)                    (((__Val__) <<  UFC23_C_ZCD_LVL_Pos)                &   UFC23_C_ZCD_LVL_Msk)
#define UFC23_C_ZCD_LVL_GET(__Val__)                    (((__Val__) &   UFC23_C_ZCD_LVL_Msk)                >>  UFC23_C_ZCD_LVL_Pos)
#define UFC23_C_ZCC_MODE_SET(__Val__)                   (((__Val__) <<  UFC23_C_ZCC_MODE_Pos)               &   UFC23_C_ZCC_MODE_Msk)
#define UFC23_C_ZCC_MODE_GET(__Val__)                   (((__Val__) &   UFC23_C_ZCC_MODE_Msk)               >>  UFC23_C_ZCC_MODE_Pos)
#define UFC23_C_ZCC_INIT_EN_SET(__Val__)                (((__Val__) <<  UFC23_C_ZCC_INIT_EN_Pos)            &   UFC23_C_ZCC_INIT_EN_Msk)
#define UFC23_C_ZCC_INIT_EN_GET(__Val__)                (((__Val__) &   UFC23_C_ZCC_INIT_EN_Msk)            >>  UFC23_C_ZCC_INIT_EN_Pos)

//// Register UFC23_CR_USM_FBG_MCTRL (0xAB)
#define UFC23_C_FBG_SEL_SET(__Val__)                    (((__Val__) <<  UFC23_C_FBG_SEL_Pos)                &   UFC23_C_FBG_SEL_Msk)
#define UFC23_C_FBG_SEL_GET(__Val__)                    (((__Val__) &   UFC23_C_FBG_SEL_Msk)                >>  UFC23_C_FBG_SEL_Pos)
#define UFC23_C_FBG_LR_CLK_DIV_SET(__Val__)             (((__Val__) <<  UFC23_C_FBG_LR_CLK_DIV_Pos)         &   UFC23_C_FBG_LR_CLK_DIV_Msk)
#define UFC23_C_FBG_LR_CLK_DIV_GET(__Val__)             (((__Val__) &   UFC23_C_FBG_LR_CLK_DIV_Msk)         >>  UFC23_C_FBG_LR_CLK_DIV_Pos)
#define UFC23_C_FBG_FBNUM_SET(__Val__)                  (((__Val__) <<  UFC23_C_FBG_FBNUM_Pos)              &   UFC23_C_FBG_FBNUM_Msk)
#define UFC23_C_FBG_FBNUM_GET(__Val__)                  (((__Val__) &   UFC23_C_FBG_FBNUM_Msk)              >>  UFC23_C_FBG_FBNUM_Pos)
#define UFC23_C_FBG_FBSP_SET(__Val__)                   (((__Val__) <<  UFC23_C_FBG_FBSP_Pos)               &   UFC23_C_FBG_FBSP_Msk)
#define UFC23_C_FBG_FBSP_GET(__Val__)                   (((__Val__) &   UFC23_C_FBG_FBSP_Msk)               >>  UFC23_C_FBG_FBSP_Pos)
#define UFC23_C_FSPLITWID_SET(__Val__)                  (((__Val__) <<  UFC23_C_FSPLITWID_Pos)              &   UFC23_C_FSPLITWID_Msk)
#define UFC23_C_FSPLITWID_GET(__Val__)                  (((__Val__) &   UFC23_C_FSPLITWID_Msk)              >>  UFC23_C_FSPLITWID_Pos)
#define UFC23_C_FBG_HR_CLK_DIV_SET(__Val__)             (((__Val__) <<  UFC23_C_FBG_HR_CLK_DIV_Pos)         &   UFC23_C_FBG_HR_CLK_DIV_Msk)
#define UFC23_C_FBG_HR_CLK_DIV_GET(__Val__)             (((__Val__) &   UFC23_C_FBG_HR_CLK_DIV_Msk)         >>  UFC23_C_FBG_HR_CLK_DIV_Pos)

//// Register UFC23_CR_USM_FBG_HRC (0xAC)
#define UFC23_C_FBG_HR_CALIB_SET(__Val__)               (((__Val__) <<  UFC23_C_FBG_HR_CALIB_Pos)           &   UFC23_C_FBG_HR_CALIB_Msk)
#define UFC23_C_FBG_HR_CALIB_GET(__Val__)               (((__Val__) &   UFC23_C_FBG_HR_CALIB_Msk)           >>  UFC23_C_FBG_HR_CALIB_Pos)
#define UFC23_C_FBG_HR_CLB_SEL_SET(__Val__)             (((__Val__) <<  UFC23_C_FBG_HR_CLB_SEL_Pos)         &   UFC23_C_FBG_HR_CLB_SEL_Msk)
#define UFC23_C_FBG_HR_CLB_SEL_GET(__Val__)             (((__Val__) &   UFC23_C_FBG_HR_CLB_SEL_Msk)         >>  UFC23_C_FBG_HR_CLB_SEL_Pos)
#define UFC23_C_FBG_HR_TRIM_SET(__Val__)                (((__Val__) <<  UFC23_C_FBG_HR_TRIM_Pos)            &   UFC23_C_FBG_HR_TRIM_Msk)
#define UFC23_C_FBG_HR_TRIM_GET(__Val__)                (((__Val__) &   UFC23_C_FBG_HR_TRIM_Msk)            >>  UFC23_C_FBG_HR_TRIM_Pos)
#define UFC23_C_FBG_CALIB_MODE_SET(__Val__)             (((__Val__) <<  UFC23_C_FBG_CALIB_MODE_Pos)         &   UFC23_C_FBG_CALIB_MODE_Msk)
#define UFC23_C_FBG_CALIB_MODE_GET(__Val__)             (((__Val__) &   UFC23_C_FBG_CALIB_MODE_Msk)         >>  UFC23_C_FBG_CALIB_MODE_Pos)

//// Register UFC23_CR_FEP_ANA_CTRL1 (0xAD)
#define UFC23_C_HS_OSC_TRIM_SET(__Val__)                (((__Val__) <<  UFC23_C_HS_OSC_TRIM_Pos)            &   UFC23_C_HS_OSC_TRIM_Msk)
#define UFC23_C_HS_OSC_TRIM_GET(__Val__)                (((__Val__) &   UFC23_C_HS_OSC_TRIM_Msk)            >>  UFC23_C_HS_OSC_TRIM_Pos)
#define UFC23_C_HS_OSC_CFG_SET(__Val__)                 (((__Val__) <<  UFC23_C_HS_OSC_CFG_Pos)             &   UFC23_C_HS_OSC_CFG_Msk)
#define UFC23_C_HS_OSC_CFG_GET(__Val__)                 (((__Val__) &   UFC23_C_HS_OSC_CFG_Msk)             >>  UFC23_C_HS_OSC_CFG_Pos)
#define UFC23_C_LS_OSC_CFG_SET(__Val__)                 (((__Val__) <<  UFC23_C_LS_OSC_CFG_Pos)             &   UFC23_C_LS_OSC_CFG_Msk)
#define UFC23_C_LS_OSC_CFG_GET(__Val__)                 (((__Val__) &   UFC23_C_LS_OSC_CFG_Msk)             >>  UFC23_C_LS_OSC_CFG_Pos)
#define UFC23_C_PMU_BG_TRIM_SET(__Val__)                (((__Val__) <<  UFC23_C_PMU_BG_TRIM_Pos)            &   UFC23_C_PMU_BG_TRIM_Msk)
#define UFC23_C_PMU_BG_TRIM_GET(__Val__)                (((__Val__) &   UFC23_C_PMU_BG_TRIM_Msk)            >>  UFC23_C_PMU_BG_TRIM_Pos)
#define UFC23_C_PMU_BIAS_TRIM_SET(__Val__)              (((__Val__) <<  UFC23_C_PMU_BIAS_TRIM_Pos)          &   UFC23_C_PMU_BIAS_TRIM_Msk)
#define UFC23_C_PMU_BIAS_TRIM_GET(__Val__)              (((__Val__) &   UFC23_C_PMU_BIAS_TRIM_Msk)          >>  UFC23_C_PMU_BIAS_TRIM_Pos)
#define UFC23_C_PMU_LDO_SEL_SET(__Val__)                (((__Val__) <<  UFC23_C_PMU_LDO_SEL_Pos)            &   UFC23_C_PMU_LDO_SEL_Msk)
#define UFC23_C_PMU_LDO_SEL_GET(__Val__)                (((__Val__) &   UFC23_C_PMU_LDO_SEL_Msk)            >>  UFC23_C_PMU_LDO_SEL_Pos)
#define UFC23_C_ZCD_IBSEL_SET(__Val__)                  (((__Val__) <<  UFC23_C_ZCD_IBSEL_Pos)              &   UFC23_C_ZCD_IBSEL_Msk)
#define UFC23_C_ZCD_IBSEL_GET(__Val__)                  (((__Val__) &   UFC23_C_ZCD_IBSEL_Msk)              >>  UFC23_C_ZCD_IBSEL_Pos)
#define UFC23_C_ZCD_DAC_VREFN_SEL_SET(__Val__)          (((__Val__) <<  UFC23_C_ZCD_DAC_VREFN_SEL_Pos)      &   UFC23_C_ZCD_DAC_VREFN_SEL_Msk)
#define UFC23_C_ZCD_DAC_VREFN_SEL_GET(__Val__)          (((__Val__) &   UFC23_C_ZCD_DAC_VREFN_SEL_Msk)      >>  UFC23_C_ZCD_DAC_VREFN_SEL_Pos)
#define UFC23_C_PGA_GPIO_SEL_SET(__Val__)               (((__Val__) <<  UFC23_C_PGA_GPIO_SEL_Pos)           &   UFC23_C_PGA_GPIO_SEL_Msk)
#define UFC23_C_PGA_GPIO_SEL_GET(__Val__)               (((__Val__) &   UFC23_C_PGA_GPIO_SEL_Msk)           >>  UFC23_C_PGA_GPIO_SEL_Pos)
#define UFC23_C_TX_CAP_MODE_SET(__Val__)                (((__Val__) <<  UFC23_C_TX_CAP_MODE_Pos)            &   UFC23_C_TX_CAP_MODE_Msk)
#define UFC23_C_TX_CAP_MODE_GET(__Val__)                (((__Val__) &   UFC23_C_TX_CAP_MODE_Msk)            >>  UFC23_C_TX_CAP_MODE_Pos)
#define UFC23_C_USVREF_CAP_EN_SET(__Val__)              (((__Val__) <<  UFC23_C_USVREF_CAP_EN_Pos)          &   UFC23_C_USVREF_CAP_EN_Msk)
#define UFC23_C_USVREF_CAP_EN_GET(__Val__)              (((__Val__) &   UFC23_C_USVREF_CAP_EN_Msk)          >>  UFC23_C_USVREF_CAP_EN_Pos)

//// Register UFC23_CR_FEP_ANA_CTRL2 (0xAE)
#define UFC23_C_PGA_ST2_GAIN_SET(__Val__)               (((__Val__) <<  UFC23_C_PGA_ST2_GAIN_Pos)           &   UFC23_C_PGA_ST2_GAIN_Msk)
#define UFC23_C_PGA_ST2_GAIN_GET(__Val__)               (((__Val__) &   UFC23_C_PGA_ST2_GAIN_Msk)           >>  UFC23_C_PGA_ST2_GAIN_Pos)
#define UFC23_C_PGA_ST2_CBYP_SET(__Val__)               (((__Val__) <<  UFC23_C_PGA_ST2_CBYP_Pos)           &   UFC23_C_PGA_ST2_CBYP_Msk)
#define UFC23_C_PGA_ST2_CBYP_GET(__Val__)               (((__Val__) &   UFC23_C_PGA_ST2_CBYP_Msk)           >>  UFC23_C_PGA_ST2_CBYP_Pos)
#define UFC23_C_PGA_ST1_GAIN_SET(__Val__)               (((__Val__) <<  UFC23_C_PGA_ST1_GAIN_Pos)           &   UFC23_C_PGA_ST1_GAIN_Msk)
#define UFC23_C_PGA_ST1_GAIN_GET(__Val__)               (((__Val__) &   UFC23_C_PGA_ST1_GAIN_Msk)           >>  UFC23_C_PGA_ST1_GAIN_Pos)
#define UFC23_C_PGA_ST1_CBYP_SET(__Val__)               (((__Val__) <<  UFC23_C_PGA_ST1_CBYP_Pos)           &   UFC23_C_PGA_ST1_CBYP_Msk)
#define UFC23_C_PGA_ST1_CBYP_GET(__Val__)               (((__Val__) &   UFC23_C_PGA_ST1_CBYP_Msk)           >>  UFC23_C_PGA_ST1_CBYP_Pos)
#define UFC23_C_PGA_G1_OPEN_SET(__Val__)                (((__Val__) <<  UFC23_C_PGA_G1_OPEN_Pos)            &   UFC23_C_PGA_G1_OPEN_Msk)
#define UFC23_C_PGA_G1_OPEN_GET(__Val__)                (((__Val__) &   UFC23_C_PGA_G1_OPEN_Msk)            >>  UFC23_C_PGA_G1_OPEN_Pos)
#define UFC23_C_PGA_ISEL_SET(__Val__)                   (((__Val__) <<  UFC23_C_PGA_ISEL_Pos)               &   UFC23_C_PGA_ISEL_Msk)
#define UFC23_C_PGA_ISEL_GET(__Val__)                   (((__Val__) &   UFC23_C_PGA_ISEL_Msk)               >>  UFC23_C_PGA_ISEL_Pos)
#define UFC23_C_PGA_ST1_OPAN_ENA_SET(__Val__)           (((__Val__) <<  UFC23_C_PGA_ST1_OPAN_ENA_Pos)       &   UFC23_C_PGA_ST1_OPAN_ENA_Msk)
#define UFC23_C_PGA_ST1_OPAN_ENA_GET(__Val__)           (((__Val__) &   UFC23_C_PGA_ST1_OPAN_ENA_Msk)       >>  UFC23_C_PGA_ST1_OPAN_ENA_Pos)
#define UFC23_C_PGA_ST1_OPAP_ENA_SET(__Val__)           (((__Val__) <<  UFC23_C_PGA_ST1_OPAP_ENA_Pos)       &   UFC23_C_PGA_ST1_OPAP_ENA_Msk)
#define UFC23_C_PGA_ST1_OPAP_ENA_GET(__Val__)           (((__Val__) &   UFC23_C_PGA_ST1_OPAP_ENA_Msk)       >>  UFC23_C_PGA_ST1_OPAP_ENA_Pos)
#define UFC23_C_PGA_ST2_OPA_ENA_SET(__Val__)            (((__Val__) <<  UFC23_C_PGA_ST2_OPA_ENA_Pos)        &   UFC23_C_PGA_ST2_OPA_ENA_Msk)
#define UFC23_C_PGA_ST2_OPA_ENA_GET(__Val__)            (((__Val__) &   UFC23_C_PGA_ST2_OPA_ENA_Msk)        >>  UFC23_C_PGA_ST2_OPA_ENA_Pos)
#define UFC23_C_COMPSEL_SEL_SET(__Val__)                (((__Val__) <<  UFC23_C_COMPSEL_SEL_Pos)            &   UFC23_C_COMPSEL_SEL_Msk)
#define UFC23_C_COMPSEL_SEL_GET(__Val__)                (((__Val__) &   UFC23_C_COMPSEL_SEL_Msk)            >>  UFC23_C_COMPSEL_SEL_Pos)
#define UFC23_C_R_COMPSEL_SET(__Val__)                  (((__Val__) <<  UFC23_C_R_COMPSEL_Pos)              &   UFC23_C_R_COMPSEL_Msk)
#define UFC23_C_R_COMPSEL_GET(__Val__)                  (((__Val__) &   UFC23_C_R_COMPSEL_Msk)              >>  UFC23_C_R_COMPSEL_Pos)
#define UFC23_C_C_COMPSEL_SET(__Val__)                  (((__Val__) <<  UFC23_C_C_COMPSEL_Pos)              &   UFC23_C_C_COMPSEL_Msk)
#define UFC23_C_C_COMPSEL_GET(__Val__)                  (((__Val__) &   UFC23_C_C_COMPSEL_Msk)              >>  UFC23_C_C_COMPSEL_Pos)
#define UFC23_C_RMSET_RX_SET(__Val__)                   (((__Val__) <<  UFC23_C_RMSET_RX_Pos)               &   UFC23_C_RMSET_RX_Msk)
#define UFC23_C_RMSET_RX_GET(__Val__)                   (((__Val__) &   UFC23_C_RMSET_RX_Msk)               >>  UFC23_C_RMSET_RX_Pos)
#define UFC23_C_RMSET_TX_SET(__Val__)                   (((__Val__) <<  UFC23_C_RMSET_TX_Pos)               &   UFC23_C_RMSET_TX_Msk)
#define UFC23_C_RMSET_TX_GET(__Val__)                   (((__Val__) &   UFC23_C_RMSET_TX_Msk)               >>  UFC23_C_RMSET_TX_Pos)
#define UFC23_C_SE_ENABLE_SET(__Val__)                  (((__Val__) <<  UFC23_C_SE_ENABLE_Pos)              &   UFC23_C_SE_ENABLE_Msk)
#define UFC23_C_SE_ENABLE_GET(__Val__)                  (((__Val__) &   UFC23_C_SE_ENABLE_Msk)              >>  UFC23_C_SE_ENABLE_Pos)

//// Register UFC23_CR_USM_RCV_INIT (0xAF)
#define UFC23_C_US_VR_INIT_SET(__Val__)                 (((__Val__) <<  UFC23_C_US_VR_INIT_Pos)             &   UFC23_C_US_VR_INIT_Msk)
#define UFC23_C_US_VR_INIT_GET(__Val__)                 (((__Val__) &   UFC23_C_US_VR_INIT_Msk)             >>  UFC23_C_US_VR_INIT_Pos)
#define UFC23_C_PGA_INIT_SET(__Val__)                   (((__Val__) <<  UFC23_C_PGA_INIT_Pos)               &   UFC23_C_PGA_INIT_Msk)
#define UFC23_C_PGA_INIT_GET(__Val__)                   (((__Val__) &   UFC23_C_PGA_INIT_Msk)               >>  UFC23_C_PGA_INIT_Pos)
#define UFC23_C_COMP_INIT_SET(__Val__)                  (((__Val__) <<  UFC23_C_COMP_INIT_Pos)              &   UFC23_C_COMP_INIT_Msk)
#define UFC23_C_COMP_INIT_GET(__Val__)                  (((__Val__) &   UFC23_C_COMP_INIT_Msk)              >>  UFC23_C_COMP_INIT_Pos)
#define UFC23_C_ADC_VR_INIT_SET(__Val__)                (((__Val__) <<  UFC23_C_ADC_VR_INIT_Pos)            &   UFC23_C_ADC_VR_INIT_Msk)
#define UFC23_C_ADC_VR_INIT_GET(__Val__)                (((__Val__) &   UFC23_C_ADC_VR_INIT_Msk)            >>  UFC23_C_ADC_VR_INIT_Pos)
#define UFC23_C_ADC_INIT_SET(__Val__)                   (((__Val__) <<  UFC23_C_ADC_INIT_Pos)               &   UFC23_C_ADC_INIT_Msk)
#define UFC23_C_ADC_INIT_GET(__Val__)                   (((__Val__) &   UFC23_C_ADC_INIT_Msk)               >>  UFC23_C_ADC_INIT_Pos)
#define UFC23_C_USM_INIT_MODE_SET(__Val__)              (((__Val__) <<  UFC23_C_USM_INIT_MODE_Pos)          &   UFC23_C_USM_INIT_MODE_Msk)
#define UFC23_C_USM_INIT_MODE_GET(__Val__)              (((__Val__) &   UFC23_C_USM_INIT_MODE_Msk)          >>  UFC23_C_USM_INIT_MODE_Pos)
#define UFC23_C_DCO_INIT_SET(__Val__)                   (((__Val__) <<  UFC23_C_DCO_INIT_Pos)               &   UFC23_C_DCO_INIT_Msk)
#define UFC23_C_DCO_INIT_GET(__Val__)                   (((__Val__) &   UFC23_C_DCO_INIT_Msk)               >>  UFC23_C_DCO_INIT_Pos)

//// Register UFC23_CR_USM_HIT_CTRL (0xB0)
#define UFC23_C_TOF_HIT_NO_SET(__Val__)                 (((__Val__) <<  UFC23_C_TOF_HIT_NO_Pos)             &   UFC23_C_TOF_HIT_NO_Msk)
#define UFC23_C_TOF_HIT_NO_GET(__Val__)                 (((__Val__) &   UFC23_C_TOF_HIT_NO_Msk)             >>  UFC23_C_TOF_HIT_NO_Pos)
#define UFC23_C_TOF_HIT_RLS_MODE_SET(__Val__)           (((__Val__) <<  UFC23_C_TOF_HIT_RLS_MODE_Pos)       &   UFC23_C_TOF_HIT_RLS_MODE_Msk)
#define UFC23_C_TOF_HIT_RLS_MODE_GET(__Val__)           (((__Val__) &   UFC23_C_TOF_HIT_RLS_MODE_Msk)       >>  UFC23_C_TOF_HIT_RLS_MODE_Pos)
#define UFC23_C_TOF_HIT_IGN_MODE_SET(__Val__)           (((__Val__) <<  UFC23_C_TOF_HIT_IGN_MODE_Pos)       &   UFC23_C_TOF_HIT_IGN_MODE_Msk)
#define UFC23_C_TOF_HIT_IGN_MODE_GET(__Val__)           (((__Val__) &   UFC23_C_TOF_HIT_IGN_MODE_Msk)       >>  UFC23_C_TOF_HIT_IGN_MODE_Pos)
#define UFC23_C_TOF_MULTIHIT_START_SET(__Val__)         (((__Val__) <<  UFC23_C_TOF_MULTIHIT_START_Pos)     &   UFC23_C_TOF_MULTIHIT_START_Msk)
#define UFC23_C_TOF_MULTIHIT_START_GET(__Val__)         (((__Val__) &   UFC23_C_TOF_MULTIHIT_START_Msk)     >>  UFC23_C_TOF_MULTIHIT_START_Pos)
#define UFC23_C_TOF_MULTIHIT_NO_SET(__Val__)            (((__Val__) <<  UFC23_C_TOF_MULTIHIT_NO_Pos)        &   UFC23_C_TOF_MULTIHIT_NO_Msk)
#define UFC23_C_TOF_MULTIHIT_NO_GET(__Val__)            (((__Val__) &   UFC23_C_TOF_MULTIHIT_NO_Msk)        >>  UFC23_C_TOF_MULTIHIT_NO_Pos)

//// Register UFC23_CR_USM_WVM (0xB1)
#define UFC23_C_USM_FHL_UP_SET(__Val__)                 (((__Val__) <<  UFC23_C_USM_FHL_UP_Pos)             &   UFC23_C_USM_FHL_UP_Msk)
#define UFC23_C_USM_FHL_UP_GET(__Val__)                 (((__Val__) &   UFC23_C_USM_FHL_UP_Msk)             >>  UFC23_C_USM_FHL_UP_Pos)
#define UFC23_C_USM_FHL_DN_SET(__Val__)                 (((__Val__) <<  UFC23_C_USM_FHL_DN_Pos)             &   UFC23_C_USM_FHL_DN_Msk)
#define UFC23_C_USM_FHL_DN_GET(__Val__)                 (((__Val__) &   UFC23_C_USM_FHL_DN_Msk)             >>  UFC23_C_USM_FHL_DN_Pos)
#define UFC23_C_USM_AM_PD_1_SET(__Val__)                (((__Val__) <<  UFC23_C_USM_AM_PD_1_Pos)            &   UFC23_C_USM_AM_PD_1_Msk)
#define UFC23_C_USM_AM_PD_1_GET(__Val__)                (((__Val__) &   UFC23_C_USM_AM_PD_1_Msk)            >>  UFC23_C_USM_AM_PD_1_Pos)
#define UFC23_C_USM_AM_PD_2_SET(__Val__)                (((__Val__) <<  UFC23_C_USM_AM_PD_2_Pos)            &   UFC23_C_USM_AM_PD_2_Msk)
#define UFC23_C_USM_AM_PD_2_GET(__Val__)                (((__Val__) &   UFC23_C_USM_AM_PD_2_Msk)            >>  UFC23_C_USM_AM_PD_2_Pos)
#define UFC23_C_USM_AM_PD_3_SET(__Val__)                (((__Val__) <<  UFC23_C_USM_AM_PD_3_Pos)            &   UFC23_C_USM_AM_PD_3_Msk)
#define UFC23_C_USM_AM_PD_3_GET(__Val__)                (((__Val__) &   UFC23_C_USM_AM_PD_3_Msk)            >>  UFC23_C_USM_AM_PD_3_Pos)
#define UFC23_C_AM_VEXTSEL_SET(__Val__)                 (((__Val__) <<  UFC23_C_AM_VEXTSEL_Pos)             &   UFC23_C_AM_VEXTSEL_Msk)
#define UFC23_C_AM_VEXTSEL_GET(__Val__)                 (((__Val__) &   UFC23_C_AM_VEXTSEL_Msk)             >>  UFC23_C_AM_VEXTSEL_Pos)

//// Register UFC23_CR_USM_MASK_HR_WIN (0xB2)
#define UFC23_C_USM_MASK_HR_WIN_UP_SET(__Val__)         (((__Val__) <<  UFC23_C_USM_MASK_HR_WIN_UP_Pos)     &   UFC23_C_USM_MASK_HR_WIN_UP_Msk)
#define UFC23_C_USM_MASK_HR_WIN_UP_GET(__Val__)         (((__Val__) &   UFC23_C_USM_MASK_HR_WIN_UP_Msk)     >>  UFC23_C_USM_MASK_HR_WIN_UP_Pos)
#define UFC23_C_USM_MASK_HR_WIN_DN_SET(__Val__)         (((__Val__) <<  UFC23_C_USM_MASK_HR_WIN_DN_Pos)     &   UFC23_C_USM_MASK_HR_WIN_DN_Msk)
#define UFC23_C_USM_MASK_HR_WIN_DN_GET(__Val__)         (((__Val__) &   UFC23_C_USM_MASK_HR_WIN_DN_Msk)     >>  UFC23_C_USM_MASK_HR_WIN_DN_Pos)

//// Register UFC23_SR_DEVICE_ID (0xFF)
#define UFC23_SR_DEVICE_ID_GET(__Val__)                 (((__Val__) &   UFC23_C_SR_DEVICE_ID_Msk)           >>  UFC23_C_SR_DEVICE_ID_Pos)

//// Register Frontend Error Flag register
#define UFC23_F_FE_BUNDLE_NO_GET(__Val__)               (((__Val__) &   UFC23_FES_USM_BUNDLE_NUMBER_Msk)    >>  UFC23_FES_USM_BUNDLE_NUMBER_Pos)

#endif /* SCIOSENSE_UFC23_MACROS_H_ */